let posts = [{
    "author": "Tagesschau",
    "description": "Topaktuelle Nachtrichten auf dem Pfad der Wahrheit #Freiheit",
    "image": "img/tagesschau.jpg",
    "imageheader": "img/tagesschauheader.jpg",
    'location': 'Berlin',
    'likes': 123,
    "comments": [],
}, {
    "author": "Bild",
    "description": "Heute Verfasst, Heute gedruckt, Bild dir deine Meinung #Bildzeitung",
    "image": "img/bild.jpg",
    "imageheader": "img/bildheader.jpg",
    'location': 'Frankfurt',
    'likes': 456,
    "comments": [],
}, {
    "author": "Express",
    "description": "express, expresser, am expressten #Expresszeitung",
    "image": "img/express.jpg",
    "imageheader": "img/expressheader.jpg",
    'location': 'Hamburg',
    'likes': 789,
    "comments": [],
}, {
    "author": "Sportschau",
    "description": "Tour de France geht richtung Zielgerade! #Radsport",
    "image": "img/sportschau.jpg",
    "imageheader": "img/sportschauheader.jpg",
    'location': 'Köln',
    'likes': 369,
    "comments": [],
}, {
    "author": "ARD",
    "description": "Das Aktuelle von heute! #GEZ",
    "image": "img/daserste.jpg",
    "imageheader": "img/dasersteheader.jpg",
    'location': 'Berlin-West',
    'likes': 369,
    "comments": [],
}, {
    "author": "ZDF",
    "description": "Heute im exklusiven Interview mit... #Prominent",
    "image": "img/zdf.jpg",
    "imageheader": "img/zdfheader.jpg",
    'location': 'Freiburg',
    'likes': 369,
    "comments": [],
}, {
    "author": "RTL",
    "description": "Die neue Folge von Bauer sucht Frau! #Ehe",
    "image": "img/rtl.jpg",
    "imageheader": "img/rtlheader.jpg",
    'location': 'Düsseldorf',
    'likes': 369,
    "comments": [],
}, {
    "author": "Prosieben",
    "description": "um 20:15 Uhr ein mega Blockbuster! #Cinema",
    "image": "img/prosieben.jpg",
    "imageheader": "img/prosiebenheader.jpg",
    'location': 'Bremen',
    'likes': 369,
    "comments": [],
}, {
    "author": "Netflix",
    "description": "Wann und wo du willst! #Filme&Serien",
    "image": "img/netflix.jpg",
    "imageheader": "img/netflixheader.jpg",
    'location': 'London',
    'likes': 369,
    "comments": [],
},
];